version: '2'
services:
    nginx:
        image: nginx:1.11.5
        ports:
            - "80:80"
        volumes:
            - ./code/:/data/webroot/:ro
        #    - ./config/nginx/:/etc/nginx/:ro
    php-fpm:
        image: c3t3m3/docker-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./code/:/data/webroot/:ro
        #    - ./config/php.ini:/usr/local/etc/php/php.ini:ro
    redis:
        image: redis:3.2.4
        ports:
            - "6379:6379"
        volumes:
            - ./confog/redis.conf://usr/local/etc/redis/redis.conf:ro
